### ISSUE TITLE
Still unable to connect to device

### ISSUE THREAD

**Issue by kr428** [hannesschulze/conecto#12]
Rebuilt conecto after updating git (seeing #8 was fixed), still am unable to connect conecto to my mobile phone. Tried both a kubuntu Live ISO (with kdeconnect) and a GNOME installation (gsconnect) in my network; in both cases, connecting phone and laptop were a breeze. Neither from the phone or from conecto, I am unable to even find any device on my network. Unfortunately launching conecto -d didn't come up with any new information. Already disabled firewalls both on my laptop and my smartphone, just in case. Any way to debug what's happening here?
Thanks in advance,
Kristian

**Comment by sebasvisser** [comment]
Have the same problem.
Only thing I found using -d was:

`[DEBUG 14:52:56.295421] DeviceManager.vala:76: Error loading cache file: No such file or directory
[DEBUG 14:52:56.295530] Discovery.vala:41: Start listening for new devices at: 0.0.0.0:1714
Could not aquire name
`

**Comment by eltondecerqueira** [comment]
Same mistake here. I've tried to track what happens, but I have not found anything. The software runs but does not find any device.

**Comment by OleksiySitka** [comment]
Any news on this issue? I have the same situation here

**Comment by sebasvisser** [comment]
I gave up a little after my last comment..

**Comment by OleksiySitka** [comment]
I got it to pair somehow, I think it has something to do with installing [mconnect](https://github.com/bboozzoo/mconnect), as mentioned in #14. But the app crashes all the time, so I also gave up

**Comment by hannesschulze** [comment]
Hey everyone,

I know that it's been a while since I've last updated this project, sorry for the delay. I've been really busy working on a huge project that might be released later this year but with the current situation, I was able to get back to Conecto.

I've learned a lot in the past months and I have actually moved away from Vala towards C++, so this project became kind of unmaintainable for me (as some have already noticed, this repo also contains a really old copy of mconnect).

Since my original goal has always been to rewrite the UI (#3) and given the outdated state this project is currently in, last week I have decided to rewrite it in C++ (see my branch `c++-rewrite`). I have based my code on a more up to date version of mconnect (but without providing Dbus interfaces). I have already implemented the basic structure of the core library – what's still missing are plugins (capabilities), the GUI and more unit tests. Because of this, I am going to close all issues related to the "old" implementation (including this one)

**Comment by hannesschulze** [comment]
To everyone who has experienced issues with pairing recently:

In the new version, it should now be possible to pair new devices and unpair them from the UI. It would be great if someone could check if this issue still persists :smile: 

It's on the `new-ui` branch

**Comment by kr428** [comment]
Hi there, thanks for taking the time to revive this. Unfortunately: No. :( Effect's still the same: KDE Connect installed on tablet and smartphone and both are unable to see the laptop running Conecto. Any debugging output I could provide?

**Comment by hannesschulze** [comment]
Hi @kr428 and first of all, thanks for testing. I still can't reproduce this issue on my system.

Can you please confirm that you also don't see your phone or device from Conecto? It should be listed under "Available":
![Screenshot von 2020-04-15 08 46 01@2x](https://user-images.githubusercontent.com/43932053/79306858-38e7ee80-7ef6-11ea-8145-cf20c5a49616.png)

A few times I've seen that you have to manually refresh in the KDE Connect app, but I don't believe that's the problem.

There are a few debugging steps you can do:
- Run Conecto using `G_MESSAGES_DEBUG=all com.github.hannesschulze.conecto` to get additional output
- Use wireshark to monitor the Discovery port. Before you launch Conecto, start Wireshark (possibly with root privileges) and use the following filter: `tcp.port == 1716 && tcp`. Port 1716 is the port used for discovery so you should at least see some packets.

I might add that I have not tested Conecto on elementary OS yet (I'm currently on Fedora) so that older packages could also be another reason (although pretty unlikely). What system are you using?

Please make sure to run `git pull` since I'm pretty actively developing Conecto currently :)

**Comment by kr428** [comment]
Well, after playing around with it a bit and re-installing KDE Connect on both tablet and smartphone, it seems to generally (at least) connect now. So guess this was in some way "my environments" fault. Thanks. :)

**Comment by hannesschulze** [comment]
That's great to hear :)
