### ISSUE TITLE
Crashing after pairing a device

### ISSUE THREAD

**Issue by kolgza** [hannesschulze/conecto#5]
Conecto crashes after attempting to pair with KDE Connect on my Essential PH-1. 

[Here is the log.](https://gist.github.com/kolgza/e6554c19e45c949c3b1ca5626b44ae89)

Is more information necessary?

**Comment by hannesschulze** [comment]
How did you try to connect your phone? Did you switch the ToggleButton from the app or did you select your PC from the KDEConnect app on android?

Also, could you please show the contents of `/com/github/hannesschulze/conecto` using dconf-editor?

**Comment by hannesschulze** [comment]
Another idea I just had: Did you already connect your phone using EOSConnect? If so, did you disconnect it using the KDEConnect app?

**Comment by kolgza** [comment]
In this case, it crashes when it crashes when I request pairing from my phone.

[ConectoCrash.zip](https://github.com/hannesschulze/conecto/files/2800326/ConectoCrash.zip)

**Comment by hannesschulze** [comment]
Could you please (if it isn't installed already) install dconf-editor, open it and navigate to `/com/github/hannes/hannesschulze/conecto` if it exists and take a screenshot of the contents (and maybe the `settings/devices` folder inside)?

I think the app is trying to access some keys there but that doesn't work...

**Comment by hannesschulze** [comment]
I think this is the problem, since there is a check for ".settings.device" - that's where the warning `[WARNING 12:56:40.970141] Device.vala:417: Unable to get config for device 814a03b474008684` is coming from. I think the app is then trying to access keys in it anyway which leads to the problem (this is definitely not supposed to happen, I'll look into this further later).

What's weird is that the device is actually listed as "Connected". Have you used EOSConnect before?

What you might want to try now is:
1. Remove old configurations using `rm -Rf ~/.cache/mconnect/`
1. Install the application again
1. If there is already an entry in the KDEConnect app on Android, remove it

Please report back if that works or not :)

**Comment by DanyGee** [comment]
I have the same issue - program crashes after trying to pair the device (LGv30).
Tried trough app toggle and KDE connect - same deal.
```
com.github.hannesschulze.conecto 
** Message: 19:31:43.421: Conecto.vala:115: Report any issues/bugs you might find to https://github.com/hannesschulze/conecto/issues
[INFO 19:31:43.421329] Application.vala:155: Conecto version: 0.1
[INFO 19:31:43.421348] Application.vala:157: Kernel version: 4.15.0-45-generic
[WARNING 19:31:43.480162] Device.vala:417: Unable to get config for device fe73b145aea0d86a
[FATAL 19:31:43.481381] [GLib-GIO] g_settings_get_value: assertion 'G_IS_SETTINGS (settings)' failed
[FATAL 19:31:43.481405] [GLib] g_variant_get_string: assertion 'value != NULL' failed
[FATAL 19:31:43.481425] [GLib] g_variant_unref: assertion 'value != NULL' failed
[FATAL 19:31:43.484173] conecto_widgets_plugin_list_box_update_ui: assertion 'plugins_map != NULL' failed
[FATAL 19:31:43.484983] [GLib-GIO] g_settings_bind_with_mapping: assertion 'G_IS_SETTINGS (settings)' failed
**
Gtk:ERROR:../../../../gtk/gtkcssnode.c:319:lookup_in_global_parent_cache: assertion failed: (node->cache == NULL)
Aborted
```

**Comment by aadilayub** [comment]
I experienced this same issue when trying to connect to my phone by clicking on the toggle in the eOS app. Couldn't connect via the KDEconnect app since my laptop wasn't showing up in the devices list.

**Comment by hannesschulze** [comment]
See https://github.com/hannesschulze/conecto/issues/12#issuecomment-607424726
